### PR TITLE
Updated packages and adding FluxLifeCycleStep to router

### PR DESCRIPTION
**Pull request by nojaf**
I think this fixes the issues people have on #11.
All the tests still ran fine, but you better double check I guess.

### CODE REVIEW

**Comment by bzd2000** [comment]
Hello,

I have still the same error if I use your version.

**Comment by nojaf** [comment]
September release?

**Comment by bzd2000** [comment]
yes. 

Is it only a problem of not using the right aurelia-router version?

**Comment by nojaf** [comment]
Yes I think so

**Pull request closed without merging**
